// AUTO-GENERATED by scripts/generate-endpoints.js -- do not edit by hand.
// Regenerate with `npm run generate` after changing accounts in config.js.

// GET /api/tweets/FNBRintel
const { handleTweets } = require("../../lib/handler");

module.exports = function handler(req, res) {
  return handleTweets(req, res, { account: "FNBRintel" });
};

module.exports.config = { maxDuration: 120 };
